version: "3.10"

services:
  db:
    image: postgres:13-alpine3.14
    container_name: electronics_sales_db
    env_file:
      - .env_docker
    ports:
      - 5432:5432

  app:
    container_name: electronics_sales_app
    restart: on-failure
    entrypoint: ./boot.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_docker
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db