# Generated by Django 4.1.3 on 2022-11-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the object')),
                ('staff', models.CharField(max_length=255, verbose_name='Staff')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Debt')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_element', to='main.contact', verbose_name='Contact details')),
            ],
            options={
                'verbose_name': 'Network object',
                'verbose_name_plural': 'Network objects',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('model', models.CharField(db_index=True, max_length=25)),
                ('release_date', models.DateField()),
                ('network_elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.networkelement')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_object', models.CharField(choices=[('Завод', 'Завод'), ('Дистрибьютор', 'Дистрибьютор'), ('Дилерский центр', 'Дилерский центр'), ('Крупная розничная сеть', 'Крупная розничная сеть'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], max_length=255)),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='main.networkelement')),
            ],
        ),
        migrations.AddField(
            model_name='networkelement',
            name='provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='main.objectrelationship'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(db_index=True, max_length=10)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='main.contact')),
            ],
        ),
    ]
